backend:
  name: git-gateway
#  name: 'test-repo'
  branch: master
media_folder: static/img
public_folder: /img
display_url: https://urvastemesi.ee

collections:
  - name: "blog"
    label: "Uudised"
    folder: "src/pages/uudised"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Pealkiri", name: "title", widget: "string"}
      - {label: "Lisamise kuup채ev", name: "date", widget: "datetime"}
      - {label: "Sisu", name: "body", widget: "markdown"}
  - name: "product"
    label: "Tooted"
    folder: "src/pages/tooted"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Lisamise kuup채ev", name: "date", widget: "datetime"}
      - {label: "Pilt", name: "picture", widget: image}
      - {label: "Hind", name: "price", widget: "number", valueType: "float"}
      - {label: "L체hikirjeldus", name: "description", widget: "text"}
      - {label: "Pikk kirjeldus", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Lehed"
    files:
      - file: "src/pages/index.md"
        label: "Avaleht"
        name: "avaleht"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
        - {label: "Suur tekst", name: "hero", widget: "string"}
        - {label: "B채nner", name: "heroImage", widget: image}
        - {label: "Tellimisvormi pealkiri", name: "formTitle", widget: "string"}
        - {label: "Tellimisvormi kirjeldus", name: "formDescription", widget: "string"}
        - {label: "Kas vorm on aktiivne?", name: "isFormActive", widget: "boolean"}
        - {label: "Mitteaktiivse vormi asemel tekst", name: "notActiveDescription", widget: "string"}
        - {label: "Avalehe pilt 1", name: "picture1", widget: image}
        - {label: "Lehe sisu", name: "body", widget: "markdown"}
        - {label: Jalus, name: footer, widget: object, fields: [{label: "Jaluse tekst", name: "text", widget: "string"}, {label: "Telefoni nr", name: "telephone", widget: "string"}, {label: "E-mail", name: "email", widget: "string"}, {label: "Aadress", name: "address", widget: "string"}]}
      - file: "src/pages/galerii/index.md"
        label: "Galerii"
        name: "galerii"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Pealkiri", name: "title", widget: "string"}
          - {label: "Sisu", name: "body", widget: "markdown"}